### ISSUE TITLE
0.1.4 strange values ?

### ISSUE THREAD

**Issue by Eddie-BS** [jakenl/domoticz_solarbattery#4]
Hi,
I upgraded to 0.1.4 this morning and I noticed strange values, don't know if this is temporary or intended behaviour ?

<img width="1211" alt="Screenshot 2021-04-10 at 10 05 26" src="https://user-images.githubusercontent.com/10174704/114263223-92d5a400-99e4-11eb-9c0e-f27436181c3e.png">

at least the "lost solar energy" is unexpected ...

**Comment by jakenl** [comment]
I accidentally deleted a line of code. Therefore the script is executed at every P1-meter update. This is now restored and the script has the same behaviour as in version 0.1.3
